### ISSUE TITLE
Break page

### ISSUE THREAD

**Issue by danicotillas** [mlaa/mla-academic-interests#2]
Hi @modelm , congratulations for this work on MLA!
I´m trying to make a project and use the goodies you have in here as it appear on hcommons.org
Now, the problem is that when I install academic interest it breaks my page at the footer.
Any ideas why?

**Comment by modelm** [comment]
Hi @danicotillas, thank you for your interest in this project!

Can you provide any more detail about the problem? What exactly breaks? Are there any errors or notices on the page or in the logs?

**Comment by danicotillas** [comment]
I´m working on local so I don´t see any log.
I have activated MLA Commons Profile and MLA Academic Interests and it happens as I show you on the screenshot.
![captura de pantalla 2017-06-22 12 06 04](https://user-images.githubusercontent.com/7635775/27444107-49c747b0-5743-11e7-83be-ce8b0232c8c7.png)

There is nothing below Academic Interest, it just end it there.

**Comment by modelm** [comment]
Have you run the migrate script included with the profile plugin?

(Don't just run it without understanding what it does - it will try and move xprofile data around to fit the new field schema)

**Comment by danicotillas** [comment]
No I don´t and I think I wouldn´t know how to do it. Do you have any instructions?

**Comment by modelm** [comment]
Apologies in advance for the wall of text. The short answer is it's probably not going to work as-is unless you write your own migration script.


Unfortunately it's a little complicated at the moment, because a lot of the logic is based on some details specific to MLA Commons (and now Humanities Commons). As far as I know you're the first person other than ourselves to try and use this plugin.

The instructions you'll need will depend on your current data. Right now the only way to correctly set up the profile plugin is write your own version of the migrate script to create the required fields, and make sure it handles any existing xprofile data you plan to migrate to the new fields.

Although there's no easy installation method at the moment without writing your own migration code, I plan to make a simpler method where it will just install the fields and not migrate anything - that should work on any site with no data dependencies. I should also remove some plugin dependencies, since technically the academic interests taxonomy isn't required to use the rest of the profile plugin (and the block/follow plugins are also only a small part of the overall features, so you can do without those too once I clean up a few things). Once I have a better idea of your use case I can start thinking about how best to support it as I start implementing these improvements. So - can you tell me about the site where you're using the profile plugin? If you think it's easier to chat on the phone or over email about this that's fine with me, just let me know.

**Comment by danicotillas** [comment]
Thanks for the wall of text, it´s very appreciated the time :)
Trying to be short as well, I´m creating a website for a University in Bolivia which features are very similar as hcommons. In fact it has been our inspiration. I was checking the code and I saw there was this great git repository so of course I thought to implement as it was. I absolutely understand the problems you are saying to me but I´m sure I won´t be able to create a migrate script myself, I have some code skills but mainly html, css.
Would be great we can exchange by email, don´t hesitate to contact me at daniel@nodocomun.org so also I can keep you updated with the progress of the _almost_ twin project.

**Comment by modelm** [comment]
Sent you an email. This issue is actually more pertinent to the profile plugin and I will be adding tasks on that repo to make the necessary changes for you to be able to use it. I'll go ahead and close this one for now.
